# Site settings
title:
email:
author:
description: Battleham
url:
analytics: UA-46567973-5

theme_color: rgba(25,207,134,1);

# Build settings
markdown: kramdown
permalink: :title/
sass:
  sass_dir: css
  
logo: assets/img/logo.png

collections:
  posts:
    output: true
    permalink: /posts/:title/
  products:
    output: true
    permalink: /products/:title/
    
platforms:
  steam:
    img: assets/img/steam.png
  itch:
    img: assets/img/itch.png
  gamejolt:
    img: assets/img/gamejolt.png
    
contact:
  mail:
    url: battlehamgames@gmail.com
    
member:
  Jon Gao:
    avatar_url: assets/img/avatar.png
    role: Director
    homepage: http://rosa89n20.github.io
    twitter_profile: <a class="twitter-timeline" data-height="300" data-theme="dark" data-link-color="#19CF86" href="https://twitter.com/jongaogame?ref_src=twsrc%5Etfw">Tweets by jongaogame</a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    