# Site settings
title: BATTLEHAM
email:
author: Jon Gao
description: We make video game, and make old timer proud!
url:
analytics: UA-46567973-5

twitter:
  username: jonjon_gao
  card: summary

social:
  name: Jon Gao
  links:
    - https://twitter.com/jonjon_gao
    - https://www.facebook.com/rosa89n20
    - https://www.linkedin.com/in/rosa89n20/
    - https://github.com/rosa89n20
    - https://gitlab.com/rosa89n20
    - https://bitbucket.org/rosa89n20/
    - https://plus.google.com/+JonGao
    - https://indienova.com/steam/developer/battleham

webmaster_verifications:
  google: NVWfnJJOjWOKeKugq5mrxh_pd9OnErjAL2D_dCjppT4
  bing: 132B3ED44F1E0BE46869727F4A42CF48
  baidu: 98kC4bDLTs

lang: en_us

theme_color: rgba(25,207,134,1);

# Build settings
markdown: kramdown
permalink: :title/
sass:
  sass_dir: css

favicon: assets/img/favicon.ico
logo: assets/img/logo.png

collections:
  posts:
    output: true
    permalink: /posts/:title/
  products:
    output: true
    permalink: /products/:title/
    
platforms:
  steam:
    img: assets/img/steam.png
  itch:
    img: assets/img/itch.png
  gamejolt:
    img: assets/img/gamejolt.png
    
contact:
  mail:
    url: battlehamgames@gmail.com
    
member:
  Jon Gao:
    avatar_url: assets/img/avatar.png
    role: Director
    homepage: http://rosa89n20.github.io
    twitter_profile: <a class="twitter-timeline" data-height="300" data-theme="dark" data-link-color="#19CF86" href="https://twitter.com/jonjon_gao?ref_src=twsrc%5Etfw">Tweets by jonjon_gao</a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    
    
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed